"""Troca tipo dos campos ano para Integer

Revision ID: 01e16ca5314e
Revises: 33ce3d37717f
Create Date: 2026-01-24 15:27:38.807956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '01e16ca5314e'
down_revision: Union[str, Sequence[str], None] = '33ce3d37717f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atas', 'ano',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="ano::integer"
    )
    # Removido! Não migrar fmd_id para Integer pois contém valores não numéricos
    # op.alter_column('ficha_medida_disciplinar', 'fmd_id',
    #     existing_type=sa.VARCHAR(),
    #     type_=sa.Integer(),
    #     existing_nullable=True,
    #     postgresql_using="fmd_id::integer"
    # )
    op.alter_column('fmd_sequencia', 'ano',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
        postgresql_using="ano::integer"
    )
    op.alter_column('pontuacao_bimestral', 'pontuacao_inicial',
        existing_type=sa.NUMERIC(precision=5, scale=2),
        type_=sa.Integer(),
        existing_nullable=True
    )
    op.alter_column('pontuacao_bimestral', 'pontuacao_atual',
        existing_type=sa.NUMERIC(precision=5, scale=2),
        type_=sa.Integer(),
        existing_nullable=True
    )
    op.alter_column('pontuacao_historico', 'ano',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="ano::integer"
    )
    op.drop_constraint('prontuario_rfo_prontuario_id_fkey', 'prontuario_rfo', type_='foreignkey')
    op.create_foreign_key(None, 'prontuario_rfo', 'prontuarios', ['prontuario_id'], ['id'])
    op.drop_constraint('prontuarios_history_prontuario_id_fkey', 'prontuarios_history', type_='foreignkey')
    op.create_foreign_key(None, 'prontuarios_history', 'prontuarios', ['prontuario_id'], ['id'])
    op.alter_column('rfo_sequencia', 'ano',
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
        postgresql_using="ano::integer"
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rfo_sequencia', 'ano',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        autoincrement=True
    )
    op.drop_constraint(None, 'prontuarios_history', type_='foreignkey')
    op.create_foreign_key('prontuarios_history_prontuario_id_fkey', 'prontuarios_history', 'prontuarios_old', ['prontuario_id'], ['id'])
    op.drop_constraint(None, 'prontuario_rfo', type_='foreignkey')
    op.create_foreign_key('prontuario_rfo_prontuario_id_fkey', 'prontuario_rfo', 'prontuarios_old', ['prontuario_id'], ['id'])
    op.alter_column('pontuacao_historico', 'ano',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True
    )
    op.alter_column('pontuacao_bimestral', 'pontuacao_atual',
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=5, scale=2),
        existing_nullable=True
    )
    op.alter_column('pontuacao_bimestral', 'pontuacao_inicial',
        existing_type=sa.Integer(),
        type_=sa.NUMERIC(precision=5, scale=2),
        existing_nullable=True
    )
    op.alter_column('fmd_sequencia', 'ano',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        autoincrement=True
    )
    # Removido! Não migrar fmd_id para Integer pois contém valores não numéricos
    # op.alter_column('ficha_medida_disciplinar', 'fmd_id',
    #     existing_type=sa.Integer(),
    #     type_=sa.VARCHAR(),
    #     existing_nullable=True
    # )
    op.alter_column('atas', 'ano',
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True
    )
    op.create_table('prontuarios_old',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('aluno_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('responsavel', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('serie', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('turma', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('telefone1', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('telefone2', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('turno', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('registros_fatos', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('circunstancias_atenuantes', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('circunstancias_agravantes', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('numero', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('deleted', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name='prontuarios_aluno_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='prontuarios_pkey')
    )
    # ### end Alembic commands ###
