"""Adiciona campo lider ao Aluno

Revision ID: 14c9f0ab5dbc
Revises: 01e16ca5314e
Create Date: 2026-02-03 17:31:03.629621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '14c9f0ab5dbc'
down_revision: Union[str, Sequence[str], None] = '01e16ca5314e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prontuarios_old')
    op.add_column('alunos', sa.Column('lider', sa.Boolean(), nullable=True))
    op.drop_column('ficha_medida_disciplinar', 'pontuacao_snapshot')
    op.drop_column('ficha_medida_disciplinar', 'comportamento_snapshot')
    op.drop_column('ocorrencias', 'lider_id')
    op.alter_column('pontuacao_historico', 'valor_delta',
               existing_type=sa.REAL(),
               type_=sa.Integer(),
               existing_nullable=True)
    # (LINHAS QUE ALTERAVAM fmd_id FORAM REMOVIDAS)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pontuacao_historico', 'valor_delta',
               existing_type=sa.Integer(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.add_column('ocorrencias', sa.Column('lider_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('ficha_medida_disciplinar', sa.Column('comportamento_snapshot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ficha_medida_disciplinar', sa.Column('pontuacao_snapshot', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('alunos', 'lider')
    op.create_table('prontuarios_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('aluno_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('responsavel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('serie', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('turma', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefone1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('telefone2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('turno', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registros_fatos', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('circunstancias_atenuantes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('circunstancias_agravantes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('numero', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], name='prontuarios_aluno_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prontuarios_pkey')
    )
    # (LINHAS QUE ALTERAVAM fmd_id FORAM REMOVIDAS)
    # ### end Alembic commands ###
