"""Adiciona usuario_cadastro_id em alunos

Revision ID: 38bd6d128366
Revises: 9566c35464b4
Create Date: 2026-01-18 11:45:23.408108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38bd6d128366'
down_revision: Union[str, Sequence[str], None] = '9566c35464b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bimestres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('inicio', sa.String(), nullable=True),
    sa.Column('fim', sa.String(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cabecalhos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('secretaria', sa.String(), nullable=True),
    sa.Column('coordenacao', sa.String(), nullable=True),
    sa.Column('escola', sa.String(), nullable=True),
    sa.Column('logo_estado', sa.String(), nullable=True),
    sa.Column('logo_escola', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('logo_prefeitura', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('circunstancias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comportamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elogios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faltas_disciplinares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('natureza', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fmd_sequencia',
    sa.Column('ano', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ano')
    )
    op.create_table('ocorrencias_removidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('removed_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfo_sequencia',
    sa.Column('ano', sa.String(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ano')
    )
    op.create_table('tabela_disciplinar_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(), nullable=True),
    sa.Column('valor', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipos_ocorrencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('aluno_nome', sa.String(), nullable=True),
    sa.Column('serie_turma', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('participants_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dados_escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabecalho_id', sa.Integer(), nullable=True),
    sa.Column('escola', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('diretor_nome', sa.String(), nullable=True),
    sa.Column('diretor_cpf', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('email_remetente', sa.String(), nullable=True),
    sa.Column('senha_email_app', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('dominio_sistema', sa.String(), nullable=True),
    sa.Column('nome_sistema', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cabecalho_id'], ['cabecalhos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ficha_medida_disciplinar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fmd_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('rfo_id', sa.Integer(), nullable=True),
    sa.Column('data_fmd', sa.String(), nullable=True),
    sa.Column('tipo_falta', sa.String(), nullable=True),
    sa.Column('medida_aplicada', sa.String(), nullable=True),
    sa.Column('descricao_falta', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('data_registro', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_falta', sa.String(), nullable=True),
    sa.Column('falta_disciplinar_ids', sa.String(), nullable=True),
    sa.Column('tipo_falta_list', sa.String(), nullable=True),
    sa.Column('relato', sa.String(), nullable=True),
    sa.Column('medida_aplicada_outra', sa.String(), nullable=True),
    sa.Column('comportamento_id', sa.Integer(), nullable=True),
    sa.Column('pontuacao_id', sa.Integer(), nullable=True),
    sa.Column('comparecimento', sa.String(), nullable=True),
    sa.Column('prazo_comparecimento', sa.String(), nullable=True),
    sa.Column('atenuantes_id', sa.String(), nullable=True),
    sa.Column('agravantes_id', sa.String(), nullable=True),
    sa.Column('gestor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('baixa', sa.String(), nullable=True),
    sa.Column('relato_faltas', sa.String(), nullable=True),
    sa.Column('itens_faltas_ids', sa.String(), nullable=True),
    sa.Column('comparecimento_responsavel', sa.String(), nullable=True),
    sa.Column('atenuantes', sa.String(), nullable=True),
    sa.Column('agravantes', sa.String(), nullable=True),
    sa.Column('pontos_aplicados', sa.Integer(), nullable=True),
    sa.Column('email_enviado_data', sa.String(), nullable=True),
    sa.Column('email_enviado_para', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['comportamento_id'], ['comportamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfo_id', sa.String(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('data_ocorrencia', sa.String(), nullable=True),
    sa.Column('observador_id', sa.Integer(), nullable=True),
    sa.Column('relato_observador', sa.String(), nullable=True),
    sa.Column('advertencia_oral', sa.String(), nullable=True),
    sa.Column('material_recolhido', sa.String(), nullable=True),
    sa.Column('data_registro', sa.String(), nullable=True),
    sa.Column('hora_ocorrencia', sa.String(), nullable=True),
    sa.Column('local_ocorrencia', sa.String(), nullable=True),
    sa.Column('tipo_ocorrencia', sa.String(), nullable=True),
    sa.Column('infracao_id', sa.Integer(), nullable=True),
    sa.Column('descricao_detalhada', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_tratamento', sa.String(), nullable=True),
    sa.Column('tipo_falta', sa.String(), nullable=True),
    sa.Column('medida_aplicada', sa.String(), nullable=True),
    sa.Column('observacao_tratamento', sa.String(), nullable=True),
    sa.Column('reincidencia', sa.String(), nullable=True),
    sa.Column('responsavel_registro_id', sa.Integer(), nullable=True),
    sa.Column('observador_nome', sa.String(), nullable=True),
    sa.Column('relato_estudante', sa.String(), nullable=True),
    sa.Column('despacho_gestor', sa.String(), nullable=True),
    sa.Column('data_despacho', sa.String(), nullable=True),
    sa.Column('falta_disciplinar_id', sa.Integer(), nullable=True),
    sa.Column('tipo_ocorrencia_text', sa.String(), nullable=True),
    sa.Column('subtipo_elogio', sa.String(), nullable=True),
    sa.Column('tratamento_tipo', sa.String(), nullable=True),
    sa.Column('observador_advertencia_oral', sa.String(), nullable=True),
    sa.Column('pontos_aplicados', sa.Integer(), nullable=True),
    sa.Column('falta_ids_csv', sa.String(), nullable=True),
    sa.Column('circunstancias_atenuantes', sa.String(), nullable=True),
    sa.Column('circunstancias_agravantes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['falta_disciplinar_id'], ['faltas_disciplinares.id'], ),
    sa.ForeignKeyConstraint(['observador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['responsavel_registro_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['tipo_ocorrencia_id'], ['tipos_ocorrencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontuacao_bimestral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('bimestre', sa.Integer(), nullable=True),
    sa.Column('pontuacao_inicial', sa.Integer(), nullable=True),
    sa.Column('pontuacao_atual', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('turma', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone1', sa.String(), nullable=True),
    sa.Column('telefone2', sa.String(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('registros_fatos', sa.String(), nullable=True),
    sa.Column('circunstancias_atenuantes', sa.String(), nullable=True),
    sa.Column('circunstancias_agravantes', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('deleted', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recuperacao_senha_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('data_criacao', sa.String(), nullable=True),
    sa.Column('expiracao', sa.String(), nullable=True),
    sa.Column('usado', sa.String(), nullable=True),
    sa.Column('data_uso', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tacs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('cabecalho_id', sa.Integer(), nullable=True),
    sa.Column('escola_text', sa.String(), nullable=True),
    sa.Column('serie', sa.String(), nullable=True),
    sa.Column('turma', sa.String(), nullable=True),
    sa.Column('responsavel', sa.String(), nullable=True),
    sa.Column('diretor_nome', sa.String(), nullable=True),
    sa.Column('fato', sa.Text(), nullable=True),
    sa.Column('prazo', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['cabecalho_id'], ['cabecalhos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telefones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocorrencias_faltas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('falta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['falta_id'], ['faltas_disciplinares.id'], ),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pontuacao_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('bimestre', sa.Integer(), nullable=True),
    sa.Column('ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('fmd_id', sa.Integer(), nullable=True),
    sa.Column('tipo_evento', sa.String(), nullable=True),
    sa.Column('valor_delta', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuario_rfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ocorrencia_id', sa.Integer(), nullable=True),
    sa.Column('prontuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ocorrencia_id'], ['ocorrencias.id'], ),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuarios_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prontuario_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('changed_at', sa.String(), nullable=True),
    sa.Column('payload_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prontuario_id'], ['prontuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tac_obrigacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tac_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tac_id'], ['tacs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tac_participantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tac_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tac_id'], ['tacs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alunos', sa.Column('usuario_cadastro_id', sa.Integer(), nullable=True))
    op.alter_column('alunos', 'matricula',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('alunos', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alunos', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alunos', 'matricula',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('alunos', 'usuario_cadastro_id')
    op.drop_table('tac_participantes')
    op.drop_table('tac_obrigacoes')
    op.drop_table('prontuarios_history')
    op.drop_table('prontuario_rfo')
    op.drop_table('pontuacao_historico')
    op.drop_table('ocorrencias_faltas')
    op.drop_table('ocorrencias_alunos')
    op.drop_table('telefones')
    op.drop_table('tacs')
    op.drop_table('recuperacao_senha_tokens')
    op.drop_table('prontuarios')
    op.drop_table('pontuacao_bimestral')
    op.drop_table('ocorrencias')
    op.drop_table('ficha_medida_disciplinar')
    op.drop_table('dados_escola')
    op.drop_table('atas')
    op.drop_table('tipos_ocorrencia')
    op.drop_table('tabela_disciplinar_config')
    op.drop_table('rfo_sequencia')
    op.drop_table('ocorrencias_removidas')
    op.drop_table('fmd_sequencia')
    op.drop_table('faltas_disciplinares')
    op.drop_table('elogios')
    op.drop_table('comportamentos')
    op.drop_table('circunstancias')
    op.drop_table('cabecalhos')
    op.drop_table('bimestres')
    # ### end Alembic commands ###
